version: '3.7'

services:
  node:
    container_name: node
    build: 
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - 8000:8000
    volumes:
      - .:/app
    command: yarn dev
    networks:
      - common
    environment:
      PORT: 8000
      MONGO_URL: 'mongodb://mongo/phimmoi'
      NODE_ENV: 'development'


  mongo: 
    container_name: mongo
    image: mongo
    ports: 
      - 27017:27017
    volumes:
      - ./data:/data/db
    networks:
      - common  
networks:
  common: 
